spring:
  jpa:
    # 테이블 생성시 data.sql 실행
    defer-datasource-initialization: true
    # 전송 쿼리 확인!
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

# 2.7x 이상부터 한글 깨짐 오류 발생하여, 아래 설정 필요
server:
  servlet:
    encoding:
      force-response: true